### ISSUE TITLE
Repo description refers to Fedora 30 instead of 31

### ISSUE THREAD

**Issue by dolph** [geerlingguy/docker-fedora31-ansible#2]
![image](https://user-images.githubusercontent.com/784187/74612150-5e0fda80-50c8-11ea-898e-ddebd350b7a5.png)

**Comment by geerlingguy** [comment]
Oops, busted for my copying-and-pasting! Thanks for pointing it out, it is fixed now.

**Comment by dolph** [comment]
I'd propose a fix if I could!

Thanks for these repos, btw, I'm really looking forward to experimenting with them (I tried to do something similar last summer and - unfortunately - ended up using vagrant + virtualbox instead).
